### ISSUE TITLE
No module named 'pydiffvg'

### ISSUE THREAD

**Issue by Ricelll** [preddy5/Im2Vec#1]
Hi. when I run the code, It occured to this problem:
`Traceback (most recent call last):
  File "eval_local.py", line 6, in <module>
    from models import *
  File "/raid/home/zhujingjie/Tools/Im2Vec-master/logs/VectorVAEnLayers/version_110/models/__init__.py", line 3, in <module>
    from .vector_vae import VectorVAE
  File "/raid/home/zhujingjie/Tools/Im2Vec-master/logs/VectorVAEnLayers/version_110/models/vector_vae.py", line 10, in <module>
    import pydiffvg`

`ModuleNotFoundError: No module named 'pydiffvg'`

I did a lot of research, but I couldn't find this 'pydiffvg' library, Could you tell me how to install it？
thx!!

**Comment by preddy5** [comment]
Hey @Ricelll 
Thank you for your interest in the work. You can find diffvg library here https://github.com/BachiLi/diffvg

Regards,
Pradyumna.
