### ISSUE TITLE
problems when training

### ISSUE THREAD

**Issue by CQNing** [preddy5/Im2Vec#11]
I run :CUDA_VISIBLE_DEVICES=1 python run.py -c configs/emoji.yaml
Traceback (most recent call last):
  File "run.py", line 116, in <module>
    runner.fit(experiment)
  File "...lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File ".../lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File ".../lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 996, in run_stage
    return self._run_train()
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_train
    self._run_sanity_check(self.lightning_module)
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1111, in _run_sanity_check
    self._evaluation_loop.reload_evaluation_dataloaders()
  File ".../lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 173, in reload_evaluation_dataloaders
    self.trainer.reset_val_dataloader(model)
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 437, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, "val")
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 398, in _reset_eval_dataloader
    num_batches = len(dataloader) if has_len(dataloader) else float("inf")
  File ".../lib/python3.7/site-packages/pytorch_lightning/utilities/data.py", line 63, in has_len
    raise ValueError("`Dataloader` returned 0 length. Please make sure that it returns at least 1 batch")
ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch

anyone training successfully can tell me how to fix it?

**Comment by preddy5** [comment]
Hey @CQNing 
Which pytorch-lighting version are you using?

**Comment by CQNing** [comment]
> Hey @CQNing
> Which pytorch-lighting version are you using?

Here are what I use now:
pytorch-lightning       1.4.2
torch                     1.8.0    
python                    3.7.10

**Comment by preddy5** [comment]
could try training with pytorch-lightning version 0.9.0

**Comment by CQNing** [comment]
> could try training with pytorch-lightning version 0.9.0

I tried this command: conda install pytorch-lightning=0.9.0 -c conda-forge
but the pytorch-lightning version changed into  0.8.5
and command:CUDA_VISIBLE_DEVICES=1 python run.py -c configs/emoji.yaml
>>Traceback (most recent call last):
  File "run.py", line 117, in <module>
    runner.fit(experiment)
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1044, in fit
    results = self.run_pretrain_routine(model)
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1185, in run_pretrain_routine
    self.reset_val_dataloader(ref_model)
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 343, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 303, in _reset_eval_dataloader
    num_batches = len(dataloader) if _has_len(dataloader) else float('inf')
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 58, in _has_len
    raise ValueError('`Dataloader` returned 0 length.'
ValueError: `Dataloader` returned 0 length. Please make sure that your Dataloader at least returns 1 batch

**Comment by CQNing** [comment]
I tried this: pip install  pytorch-lightning==0.9.0
and the pytorch-lightning version changed into 0.9.0
but it still came out those problems:
>>Traceback (most recent call last):
  File "run.py", line 117, in <module>
    runner.fit(experiment)
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1084, in fit
    results = self.accelerator_backend.train(model)
  File ".../lib/python3.7/site-packages/pytorch_lightning/accelerators/cpu_backend.py", line 39, in train
    results = self.trainer.run_pretrain_routine(model)
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1224, in run_pretrain_routine
    self._run_sanity_check(ref_model, model)
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1249, in _run_sanity_check
    self.reset_val_dataloader(ref_model)
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 337, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 299, in _reset_eval_dataloader
    num_batches = len(dataloader) if _has_len(dataloader) else float('inf')
  File ".../lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 70, in _has_len
    raise ValueError('`Dataloader` returned 0 length.'
ValueError: `Dataloader` returned 0 length. Please make sure that your Dataloader at least returns 1 batch

**Comment by preddy5** [comment]
Hey @CQNing 
Sorry for the late reply completely slipped my mind.

Could you try 
`os.path.exists(self.params['data_path'])`

here https://github.com/preddy5/Im2Vec/blob/master/experiment.py#L320 that should tell us if the folder is present or not.
If the output is true then torchvision datasets seems to have a bug and you can use the MyDataset object present in the experiment file.

**Comment by CQNing** [comment]
Hi， @preddy5 
I‘ve solved this problem. And I feel so shame that this occurs because my carelessness. 
self.sample_dataloader =  DataLoader(dataset,
                                                 batch_size= 64,  ###############
                                                 shuffle = False,
                                                 drop_last=True)
When I tried to train my dataset at first, I reduced the batch_size in emoji.yaml. And I didn't change the batch_size in DataLoader().  Emmm.... Sorry to bother you!

**Comment by preddy5** [comment]
I am glad you figured it out.
