### ISSUE TITLE
KeyError: 'z_layers

### ISSUE THREAD

**Issue by DYF-AI** [preddy5/Im2Vec#3]
```shell
(Im2Vec) dyf-ai@dyfai-b450-aorus-m:/media/dyf-ai/Code/src/projectX/Im2Vec/logs/VectorVAEnLayers/version_110$ CUDA_VISIBLE_DEVICES=0 python eval_local.py -c configs/emoji.yaml

(Im2Vec) dyf-ai@dyfai-b450-aorus-m:/media/dyf-ai/Code/src/projectX/Im2Vec/logs/VectorVAEnLayers/version_110$ CUDA_VISIBLE_DEVICES=0 python eval_local.py -c configs/emoji.yaml
/media/dyf-ai/Code/src/projectX/Im2Vec /media/dyf-ai/Code/src/projectX/Im2Vec/./data/emoji/
Using Differential Compositing
loading:  epoch=667.ckpt
/home/dyf-ai/.local/lib/python3.8/site-packages/torch/nn/functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "eval_local.py", line 54, in <module>
    experiment.sample_interpolate(save_dir=config['logging_params']['save_dir'], name=config['logging_params']['name'],
  File "/media/dyf-ai/Code/src/projectX/Im2Vec/logs/VectorVAEnLayers/version_110/experiment.py", line 214, in sample_interpolate
    interpolate_samples = self.model.naive_vector_interpolate(test_input, verbose=False)
  File "/media/dyf-ai/Code/src/projectX/Im2Vec/logs/VectorVAEnLayers/version_110/models/vector_vae_nlayers.py", line 247, in naive_vector_interpolate
    output = self.composite_fn(layers = layers)
  File "/media/dyf-ai/Code/src/projectX/Im2Vec/logs/VectorVAEnLayers/version_110/models/vector_vae_nlayers.py", line 94, in soft_composite
    z_layers = kwargs['z_layers']
KeyError: 'z_layers'
```
Some errors occurred ...

**Comment by preddy5** [comment]
Hey @DYF-AI 
could you check what https://github.com/preddy5/Im2Vec/blob/master/logs/VectorVAEnLayers/version_110/configs/emoji.yaml#L13 in you config file is? If it is soft please change it to 'hard'

**Comment by DYF-AI** [comment]
problem done, thank you...
